[pytest]
DJANGO_SETTINGS_MODULE = ryzom_django_example.settings
asyncio_mode = auto
filterwarnings =
    ignore:Accessing the database during app initialization:RuntimeWarning
markers =
    asyncio: mark test as async
