# Generated by Django 2.2.9 on 2020-02-19 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Record',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('char_field', models.CharField(max_length=50, verbose_name='Char field')),
                ('date_field', models.DateField(verbose_name='Date field')),
                ('email_field', models.EmailField(max_length=254, verbose_name='Email field')),
                ('boolean_field', models.BooleanField()),
                ('null_boolean_field', models.NullBooleanField()),
                ('choice_field', models.CharField(max_length=50, verbose_name='Choice field')),
                ('choice_radio_field', models.CharField(max_length=50, verbose_name='Choice Radio field')),
            ],
        ),
    ]
