# Generated by Django 3.1.7 on 2021-03-06 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryzom_django', '0002_auto_20210306_0614'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='subscriber_id',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
