# Generated by Django 3.1.7 on 2021-03-12 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryzom_django', '0005_client_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterUniqueTogether(
            name='registration',
            unique_together={('name', 'client')},
        ),
    ]
