# Generated by Django 3.1.7 on 2021-03-12 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryzom_django', '0006_auto_20210312_1409'),
    ]

    operations = [
        migrations.AddField(
            model_name='registration',
            name='subscriber_parent',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
