# Generated by Django 3.1.7 on 2021-03-09 12:54

from django.db import migrations, models
import django.db.models.deletion
import ryzom_django.pubsub


class Migration(migrations.Migration):

    dependencies = [
        ('ryzom_django_example', '0002_auto_20210309_0848'),
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            bases=(ryzom_django.pubsub.Publishable, models.Model),
        ),
        migrations.AlterField(
            model_name='message',
            name='room',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ryzom_django_example.room'),
        ),
    ]
