# Generated by Django 2.1.7 on 2019-02-24 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0002_tasks'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptions',
            name='parent',
            field=models.CharField(default='body', max_length=255),
            preserve_default=False,
        ),
    ]
