# Generated by Django 6.0.4 on 2026-06-15 12:13

import django.contrib.auth.models
import ryzom_django_channels.pubsub
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('ryzom_example_crud', '0002_product_group'),
    ]

    operations = [
        migrations.CreateModel(
            name='LiveUser',
            fields=[
            ],
            options={
                'verbose_name': 'user',
                'verbose_name_plural': 'users',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=(ryzom_django_channels.pubsub.Publishable, 'auth.user'),
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
