# Generated by Django 3.2.7 on 2021-11-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryzom_django_channels', '0002_remove_unused_fields'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='queryset',
            field=models.JSONField(default=list),
        ),
    ]
