# Generated by Django 3.2.12 on 2022-02-15 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ryzom_django_channels', '0004_auto_20220215_0917'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='registration',
            name='options',
        ),
    ]
