# Generated by Django 3.2.17 on 2023-03-17 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ryzom_django_channels', '0005_remove_registration_options'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscription',
            old_name='queryset',
            new_name='qs',
        ),
    ]
