# Generated by Django 6.0.4 on 2026-06-02 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryzom_django_channels', '0007_auto_20230327_1510'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='last_seen',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
