# Generated by Django 3.0.10 on 2021-01-13 18:59

import django.contrib.postgres.fields.jsonb
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ryzom', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('model_module', models.CharField(max_length=255)),
                ('model_class', models.CharField(max_length=255)),
                ('template_module', models.CharField(max_length=255)),
                ('template_class', models.CharField(max_length=255)),
            ],
        ),
        migrations.AddField(
            model_name='subscriptions',
            name='options',
            field=django.contrib.postgres.fields.jsonb.JSONField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='subscriptions',
            name='publication',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ryzom.Publication'),
        ),
        migrations.DeleteModel(
            name='Publications',
        ),
    ]
