# Generated by Django 3.0.10 on 2021-01-13 19:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ryzom', '0002_auto_20210113_1859'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Subscriptions',
            new_name='Subscription',
        ),
    ]
