# Generated by Django 3.0.12 on 2021-02-01 13:44

from django.db import migrations, models
import secrets


class Migration(migrations.Migration):

    dependencies = [
        ('ryzom', '0003_auto_20210201_1310'),
    ]

    operations = [
        migrations.AddField(
            model_name='clients',
            name='token',
            field=models.CharField(default=secrets.token_urlsafe, max_length=255, unique=True),
        ),
        migrations.DeleteModel(
            name='Tokens',
        ),
    ]
