# Generated by Django 3.0.10 on 2021-01-13 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ryzom', '0003_auto_20210113_1901'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=255, unique=True)),
                ('parent_module', models.CharField(max_length=255)),
                ('parent_class', models.CharField(max_length=255)),
            ],
        ),
    ]
