# Generated by Django 3.0.10 on 2021-01-15 14:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import ryzom.pubsub


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.CharField(max_length=1024)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            bases=(ryzom.pubsub.Publishable, models.Model),
        ),
    ]
